//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSpirit.ExamApi.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExamDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamDisplay() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeSpirit.ExamApi.Resources.ExamDisplay", typeof(ExamDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 详细解释正确答案的原因，帮助学生理解知识点 的本地化字符串。
        /// </summary>
        public static string Description_Question_Analysis {
            get {
                return ResourceManager.GetString("Description.Question.Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选题请用逗号分隔，判断题答案必须是True或False。 的本地化字符串。
        /// </summary>
        public static string Description_Question_CorrectAnswer {
            get {
                return ResourceManager.GetString("Description.Question.CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列出该题目涉及的主要知识点，用逗号分隔 的本地化字符串。
        /// </summary>
        public static string Description_Question_KnowledgePoints {
            get {
                return ResourceManager.GetString("Description.Question.KnowledgePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据题目内容生成合适的选项，单选题通常4个选项，多选题可以有更多选项 的本地化字符串。
        /// </summary>
        public static string Description_Question_Options {
            get {
                return ResourceManager.GetString("Description.Question.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为题目添加相关标签，便于分类和搜索 的本地化字符串。
        /// </summary>
        public static string Description_Question_Tags {
            get {
                return ResourceManager.GetString("Description.Question.Tags", resourceCulture);
            }
        }
    }
}
