<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <!--<PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />-->
    <!--<PackageReference Include="Microsoft.Extensions.DependencyInjection" />-->
    <!--<PackageReference Include="Microsoft.Extensions.Http" />-->
    <!--<PackageReference Include="Microsoft.Extensions.Options" />-->
    <!--<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />-->
    <!--<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />-->
    <!-- Newtonsoft.Json 通过 CodeSpirit.Shared 传递 -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CodeSpirit.Core\CodeSpirit.Core.csproj" />
    <ProjectReference Include="..\CodeSpirit.Caching\CodeSpirit.Caching.csproj" />
    <ProjectReference Include="..\..\CodeSpirit.Shared\CodeSpirit.Shared.csproj" />
  </ItemGroup>

</Project>

