<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>SKEXP0001;SKEXP0010;SKEXP0050</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.46.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Core" Version="1.46.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Anthropic" Version="1.46.0-preview" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CodeSpirit.Core\CodeSpirit.Core.csproj" />
  </ItemGroup>

</Project> 