// <auto-generated />
using System;
using CodeSpirit.FileStorageApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSpirit.FileStorageApi.Migrations
{
    [DbContext(typeof(FileStorageDbContext))]
    [Migration("20250813062151_AddTenantIdToImageMetadata")]
    partial class AddTenantIdToImageMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AccessCount")
                        .HasColumnType("bigint");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ETag")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Files_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Files_CreatedAt");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("IX_Files_ExpirationTime");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("IX_Files_FileHash");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Files_Status");

                    b.HasIndex("TenantId", "BucketName")
                        .HasDatabaseName("IX_Files_TenantId_BucketName");

                    b.HasIndex("TenantId", "Category")
                        .HasDatabaseName("IX_Files_TenantId_Category");

                    b.HasIndex("TenantId", "OriginalFileName")
                        .HasDatabaseName("IX_Files_TenantId_OriginalFileName");

                    b.HasIndex("TenantId", "StorageFileName")
                        .IsUnique()
                        .HasDatabaseName("IX_Files_TenantId_StorageFileName");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.FileReferenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConfirmedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("IX_FileReferences_ExpirationTime");

                    b.HasIndex("FileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FileReferences_Status");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("IX_FileReferences_TenantId_FileId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_FileReferences_TenantId_Status");

                    b.HasIndex("SourceService", "SourceEntityType", "SourceEntityId")
                        .HasDatabaseName("IX_FileReferences_Source");

                    b.HasIndex("TenantId", "IsTemporary", "Status")
                        .HasDatabaseName("IX_FileReferences_TenantId_IsTemporary_Status");

                    b.ToTable("FileReferences");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.ImageMetadataEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CameraModel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ColorDepth")
                        .HasColumnType("int");

                    b.Property<string>("ColorPalette")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<double>("DpiX")
                        .HasColumnType("float");

                    b.Property<double>("DpiY")
                        .HasColumnType("float");

                    b.Property<string>("ExifData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("FrameCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasAlpha")
                        .HasColumnType("bit");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnimated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateTaken")
                        .HasDatabaseName("IX_ImageMetadata_DateTaken");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("Format")
                        .HasDatabaseName("IX_ImageMetadata_Format");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_ImageMetadata_GpsLocation");

                    b.HasIndex("Width", "Height")
                        .HasDatabaseName("IX_ImageMetadata_Dimensions");

                    b.ToTable("ImageMetadata");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.VideoMetadataEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AudioChannels")
                        .HasColumnType("int");

                    b.Property<string>("AudioCodec")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AudioSampleRate")
                        .HasColumnType("int");

                    b.Property<long>("Bitrate")
                        .HasColumnType("bigint");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<double>("FrameRate")
                        .HasColumnType("float");

                    b.Property<bool>("HasAudio")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("bit");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThumbnailTimePosition")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime")
                        .HasDatabaseName("IX_VideoMetadata_CreatedTime");

                    b.HasIndex("Duration")
                        .HasDatabaseName("IX_VideoMetadata_Duration");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("VideoCodec")
                        .HasDatabaseName("IX_VideoMetadata_VideoCodec");

                    b.HasIndex("Width", "Height")
                        .HasDatabaseName("IX_VideoMetadata_Dimensions");

                    b.ToTable("VideoMetadata");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.FileReferenceEntity", b =>
                {
                    b.HasOne("CodeSpirit.FileStorageApi.Entities.FileEntity", "File")
                        .WithMany("References")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.ImageMetadataEntity", b =>
                {
                    b.HasOne("CodeSpirit.FileStorageApi.Entities.FileEntity", "File")
                        .WithOne("ImageMetadata")
                        .HasForeignKey("CodeSpirit.FileStorageApi.Entities.ImageMetadataEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.VideoMetadataEntity", b =>
                {
                    b.HasOne("CodeSpirit.FileStorageApi.Entities.FileEntity", "File")
                        .WithOne("VideoMetadata")
                        .HasForeignKey("CodeSpirit.FileStorageApi.Entities.VideoMetadataEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("CodeSpirit.FileStorageApi.Entities.FileEntity", b =>
                {
                    b.Navigation("ImageMetadata")
                        .IsRequired();

                    b.Navigation("References");

                    b.Navigation("VideoMetadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
