apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: code-spirit
  labels:
    k8s-app: identity
    qcloud-app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: identity
      qcloud-app: identity
  template:
    metadata:
      labels:
        k8s-app: identity
        qcloud-app: identity
    spec:
      containers:
      - name: identity
        image: ccr.ccs.tencentyun.com/codespirit/identity-api:master
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: identity-appsettings
      imagePullSecrets:
      - name: tcloud
---
apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: code-spirit
  labels:
    k8s-app: identity
    qcloud-app: identity
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: identity
    qcloud-app: identity