apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: code-spirit-release
  labels:
    k8s-app: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: seq
  template:
    metadata:
      labels:
        k8s-app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq
        env:
        - name: ACCEPT_EULA
          value: "Y"
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 20m
            memory: 256Mi
      imagePullSecrets:
      - name: tcloud
---
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: code-spirit-release
  labels:
    k8s-app: seq
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: ingestion
    port: 5341
    targetPort: 5341
  selector:
    k8s-app: seq