// <auto-generated />
using System;
using CodeSpirit.ExamApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSpirit.ExamApi.Migrations.MySql
{
    [DbContext(typeof(MySqlExamDbContext))]
    partial class MySqlExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamAnswerOperationLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamRecordId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionVersionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamAnswerOperationLogs_TenantId");

                    b.HasIndex("ExamRecordId", "OperationTime")
                        .HasDatabaseName("IX_ExamAnswerOperationLogs_ExamRecordId_OperationTime");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamAnswerOperationLogs_TenantId_Id");

                    b.ToTable("ExamAnswerOperationLogs", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamAnswerRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<long>("ExamRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GradedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GraderId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuestionScore")
                        .HasColumnType("int");

                    b.Property<long>("QuestionVersionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Score")
                        .HasColumnType("double");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamAnswerRecords_TenantId");

                    b.HasIndex("ExamRecordId", "OrderNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamAnswerRecords_TenantId_Id");

                    b.ToTable("ExamAnswerRecords", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamPaper", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AverageScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ConversionDecimalPlaces")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConversionRatio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ConversionTargetFullScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("EnableScoreConversion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPreviewChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int?>("OriginalPassScore")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalTotalScore")
                        .HasColumnType("int");

                    b.Property<decimal>("PassRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<string>("RandomRules")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamPapers_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamPapers_TenantId_Id");

                    b.ToTable("ExamPapers", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamPaperQuestion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamPaperId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionVersionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamPaperQuestions_TenantId");

                    b.HasIndex("ExamPaperId", "OrderNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamPaperQuestions_TenantId_Id");

                    b.ToTable("ExamPaperQuestions", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("CheatingSuspicionLevel")
                        .HasColumnType("int");

                    b.Property<string>("CheatingSuspicionRecord")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<long>("ExamSettingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GradedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GraderId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsScoreConverted")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("OriginalScore")
                        .HasColumnType("double");

                    b.Property<double?>("Score")
                        .HasColumnType("double");

                    b.Property<decimal?>("ScoreConversionRatio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ScreenSwitchCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExamSettingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamRecords_TenantId");

                    b.HasIndex("TenantId", "ExamSettingId")
                        .HasDatabaseName("IX_ExamRecords_TenantId_ExamSettingId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamRecords_TenantId_Id");

                    b.HasIndex("TenantId", "StudentId")
                        .HasDatabaseName("IX_ExamRecords_TenantId_StudentId");

                    b.ToTable("ExamRecords", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamSetting", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AllowedAttempts")
                        .HasColumnType("int");

                    b.Property<int>("AllowedScreenSwitchCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("EnableQuestionAnalysis")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableRandomOptionOrder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableRandomQuestionOrder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableViewResult")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ExamPaperId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinExamTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("StudentGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExamPaperId");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamSettings_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamSettings_TenantId_Id");

                    b.ToTable("ExamSettings", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamSettingStudentGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamSettingId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("StudentGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExamSettingId");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ExamSettingStudentGroups_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_ExamSettingStudentGroups_TenantId_Id");

                    b.ToTable("ExamSettingStudentGroups", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("MockExamId")
                        .HasColumnType("bigint");

                    b.Property<long>("PracticeSessionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PracticeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PracticeType")
                        .HasColumnType("int");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSessionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PracticeRecords_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_PracticeRecords_TenantId_Id");

                    b.HasIndex("TenantId", "StudentId")
                        .HasDatabaseName("IX_PracticeRecords_TenantId_StudentId");

                    b.ToTable("PracticeRecords", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeSession", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("PracticeSettingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSettingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PracticeSession_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_PracticeSession_TenantId_Id");

                    b.ToTable("PracticeSession");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeSetting", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<long>("ExamPaperId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("PracticeMode")
                        .HasColumnType("int");

                    b.Property<bool>("RandomizeQuestions")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowAnalysis")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExamPaperId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PracticeSettings_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_PracticeSettings_TenantId_Id");

                    b.ToTable("PracticeSettings", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Analysis")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("text");

                    b.Property<decimal>("CorrectRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("DefaultScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KnowledgePoints")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("PublishedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Questions_TenantId");

                    b.HasIndex("TenantId", "CategoryId")
                        .HasDatabaseName("IX_Questions_TenantId_CategoryId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_Questions_TenantId_Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.QuestionCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionCategories_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_QuestionCategories_TenantId_Id");

                    b.ToTable("QuestionCategories", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.QuestionVersion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Analysis")
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("DefaultScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KnowledgePoints")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_QuestionVersions_TenantId");

                    b.HasIndex("QuestionId", "Version")
                        .IsUnique();

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_QuestionVersions_TenantId_Id");

                    b.ToTable("QuestionVersions", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AdmissionTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Students_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_Students_TenantId_Id");

                    b.HasIndex("TenantId", "StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_TenantId_StudentNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.StudentGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_StudentGroups_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_StudentGroups_TenantId_Id");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.StudentGroupMapping", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("StudentGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_StudentGroupMappings_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_StudentGroupMappings_TenantId_Id");

                    b.ToTable("StudentGroupMappings", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.WrongQuestion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastWrongAnswer")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("LastWrongTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_WrongQuestions_TenantId");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("IX_WrongQuestions_TenantId_Id");

                    b.HasIndex("TenantId", "StudentId")
                        .HasDatabaseName("IX_WrongQuestions_TenantId_StudentId");

                    b.ToTable("WrongQuestions", (string)null);
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamAnswerOperationLog", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamRecord", "ExamRecord")
                        .WithMany()
                        .HasForeignKey("ExamRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamRecord");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamAnswerRecord", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamRecord", "ExamRecord")
                        .WithMany("AnswerRecords")
                        .HasForeignKey("ExamRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamRecord");

                    b.Navigation("Question");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamPaperQuestion", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamPaper", "ExamPaper")
                        .WithMany("ExamPaperQuestions")
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Question", "Question")
                        .WithMany("ExamPaperQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamPaper");

                    b.Navigation("Question");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamRecord", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamSetting", "ExamSetting")
                        .WithMany("ExamRecords")
                        .HasForeignKey("ExamSettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Student", "Student")
                        .WithMany("ExamRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSetting");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamSetting", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamPaper", "ExamPaper")
                        .WithMany()
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.StudentGroup", null)
                        .WithMany("ExamSettings")
                        .HasForeignKey("StudentGroupId");

                    b.Navigation("ExamPaper");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamSettingStudentGroup", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamSetting", "ExamSetting")
                        .WithMany("StudentGroups")
                        .HasForeignKey("ExamSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.StudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSetting");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeRecord", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.PracticeSession", "PracticeSession")
                        .WithMany("PracticeRecords")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Student", "Student")
                        .WithMany("PracticeRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeSession");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeSession", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.PracticeSetting", "PracticeSetting")
                        .WithMany()
                        .HasForeignKey("PracticeSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeSetting");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeSetting", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.ExamPaper", "ExamPaper")
                        .WithMany()
                        .HasForeignKey("ExamPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamPaper");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.Question", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.QuestionCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.QuestionCategory", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.QuestionCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.QuestionVersion", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.StudentGroupMapping", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.StudentGroup", "StudentGroup")
                        .WithMany("Students")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Student", "Student")
                        .WithMany("StudentGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.WrongQuestion", b =>
                {
                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeSpirit.ExamApi.Data.Models.Student", "Student")
                        .WithMany("WrongQuestions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamPaper", b =>
                {
                    b.Navigation("ExamPaperQuestions");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamRecord", b =>
                {
                    b.Navigation("AnswerRecords");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.ExamSetting", b =>
                {
                    b.Navigation("ExamRecords");

                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.PracticeSession", b =>
                {
                    b.Navigation("PracticeRecords");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.Question", b =>
                {
                    b.Navigation("ExamPaperQuestions");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.QuestionCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.Student", b =>
                {
                    b.Navigation("ExamRecords");

                    b.Navigation("PracticeRecords");

                    b.Navigation("StudentGroups");

                    b.Navigation("WrongQuestions");
                });

            modelBuilder.Entity("CodeSpirit.ExamApi.Data.Models.StudentGroup", b =>
                {
                    b.Navigation("ExamSettings");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
