//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSpirit.IdentityApi.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityErrors() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeSpirit.IdentityApi.Resources.IdentityErrors", typeof(IdentityErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除 {0} 个用户，但以下用户删除失败: {1} 的本地化字符串。
        /// </summary>
        public static string BatchDeletePartialSuccess {
            get {
                return ResourceManager.GetString("BatchDeletePartialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除 {0} 个用户！ 的本地化字符串。
        /// </summary>
        public static string BatchDeleteSuccess {
            get {
                return ResourceManager.GetString("BatchDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功批量导入了 {0} 个用户！ 的本地化字符串。
        /// </summary>
        public static string BatchImportSuccess {
            get {
                return ResourceManager.GetString("BatchImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法模拟已禁用的用户！ 的本地化字符串。
        /// </summary>
        public static string CannotImpersonateDisabledUser {
            get {
                return ResourceManager.GetString("CannotImpersonateDisabledUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要批量删除? 的本地化字符串。
        /// </summary>
        public static string ConfirmBatchDelete {
            get {
                return ResourceManager.GetString("ConfirmBatchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要模拟此用户登录吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmImpersonateUser {
            get {
                return ResourceManager.GetString("ConfirmImpersonateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要重置密码吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要解除用户锁定吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmUnlockUser {
            get {
                return ResourceManager.GetString("ConfirmUnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱已存在！ 的本地化字符串。
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据可供导出 的本地化字符串。
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有超级管理员可以使用模拟登录功能！ 的本地化字符串。
        /// </summary>
        public static string OnlyAdminCanImpersonate {
            get {
                return ResourceManager.GetString("OnlyAdminCanImpersonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：密码只显示一次，请及时保存! 的本地化字符串。
        /// </summary>
        public static string PasswordDisplayOnce {
            get {
                return ResourceManager.GetString("PasswordDisplayOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码已重置成功！ 的本地化字符串。
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码结果 的本地化字符串。
        /// </summary>
        public static string ResetPasswordResult {
            get {
                return ResourceManager.GetString("ResetPasswordResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已激活成功！ 的本地化字符串。
        /// </summary>
        public static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已禁用成功！ 的本地化字符串。
        /// </summary>
        public static string UserDeactivated {
            get {
                return ResourceManager.GetString("UserDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在！ 的本地化字符串。
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已成功解锁。 的本地化字符串。
        /// </summary>
        public static string UserUnlocked {
            get {
                return ResourceManager.GetString("UserUnlocked", resourceCulture);
            }
        }
    }
}
