using CodeSpirit.PdfGeneration.Options;
using CodeSpirit.PdfGeneration.Services;
using Microsoft.Extensions.Logging;
using Moq;
using PuppeteerSharp;
using Xunit;

namespace CodeSpirit.PdfGeneration.Tests;

public class PdfGenerationServiceTests
{
    private readonly Mock<ILogger<PdfGenerationService>> _loggerMock;
    private readonly Mock<ILogger<BrowserPool>> _browserPoolLoggerMock;
    private readonly PdfGenerationOptions _options;

    public PdfGenerationServiceTests()
    {
        _loggerMock = new Mock<ILogger<PdfGenerationService>>();
        _browserPoolLoggerMock = new Mock<ILogger<BrowserPool>>();
        _options = new PdfGenerationOptions
        {
            MaxConcurrentJobs = 2,
            BrowserPoolSize = 1,
            BrowserTimeout = TimeSpan.FromSeconds(30),
            Headless = true,
            RetryCount = 1
        };
    }

    [Fact(Skip = "需要浏览器环境，仅用于手动测试")]
    public async Task GeneratePdfAsync_WithValidHtml_ReturnsPdfBytes()
    {
        // Arrange
        var service = new PdfGenerationService(_options, _loggerMock.Object, _browserPoolLoggerMock.Object);
        await service.InitializeAsync();

        var html = @"
            <!DOCTYPE html>
            <html>
            <head>
                <title>Test PDF</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 20px; }
                    h1 { color: #333; }
                </style>
            </head>
            <body>
                <h1>Hello, World!</h1>
                <p>This is a test PDF document generated by PuppeteerSharp.</p>
                <p>Current time: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + @"</p>
            </body>
            </html>";

        // Act
        var pdfBytes = await service.GeneratePdfAsync(html);

        // Assert
        Assert.NotNull(pdfBytes);
        Assert.True(pdfBytes.Length > 0);
        
        // 清理
        await service.DisposeAsync();
    }

    [Fact]
    public async Task GetStatusAsync_ReturnsCorrectStatus()
    {
        // Arrange
        var service = new PdfGenerationService(_options, _loggerMock.Object, _browserPoolLoggerMock.Object);

        // Act
        var status = await service.GetStatusAsync();

        // Assert
        Assert.NotNull(status);
        Assert.False(status.IsInitialized);
        Assert.Equal(0, status.ActiveTasks);
        Assert.Equal(_options.BrowserPoolSize, status.PoolSize);
        Assert.Equal(_options.BrowserPoolSize, status.AvailableBrowsers);
        Assert.Equal(0, status.TotalTasksProcessed);
        Assert.Equal(0, status.FailedTasks);
    }

    [Fact]
    public void Constructor_WithNullOptions_ThrowsArgumentNullException()
    {
        // Act & Assert
        var exception = Assert.Throws<ArgumentNullException>(() => 
            new PdfGenerationService(null!, _loggerMock.Object, _browserPoolLoggerMock.Object));
        
        Assert.Equal("options", exception.ParamName);
    }

    [Fact]
    public void Constructor_WithNullLogger_ThrowsArgumentNullException()
    {
        // Act & Assert
        var exception = Assert.Throws<ArgumentNullException>(() => 
            new PdfGenerationService(_options, null!, _browserPoolLoggerMock.Object));
        
        Assert.Equal("logger", exception.ParamName);
    }
    
    [Fact]
    public void Constructor_WithNullBrowserPoolLogger_ThrowsArgumentNullException()
    {
        // Act & Assert
        var exception = Assert.Throws<ArgumentNullException>(() => 
            new PdfGenerationService(_options, _loggerMock.Object, null!));
        
        Assert.Equal("browserPoolLogger", exception.ParamName);
    }
}