global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using CodeSpirit.Core.Authorization;
global using CodeSpirit.Core.DependencyInjection;
global using CodeSpirit.Core;
global using CodeSpirit.Core.Attributes;
