name: CodeSpirit.Charts 单元测试

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Src/Components/CodeSpirit.Charts/**'
      - 'Src/Tests/Components/CodeSpirit.Charts.Tests/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'Src/Components/CodeSpirit.Charts/**'
      - 'Src/Tests/Components/CodeSpirit.Charts.Tests/**'
  workflow_dispatch: # 允许手动触发

jobs:
  test:
    name: 构建和测试
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 设置 .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: 恢复依赖
      run: dotnet restore Src/Tests/Components/CodeSpirit.Charts.Tests/CodeSpirit.Charts.Tests.csproj
      
    - name: 构建项目
      run: dotnet build Src/Tests/Components/CodeSpirit.Charts.Tests/CodeSpirit.Charts.Tests.csproj --no-restore --configuration Release
      
    - name: 执行测试
      run: dotnet test Src/Tests/Components/CodeSpirit.Charts.Tests/CodeSpirit.Charts.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/coverage.cobertura.xml
      
    - name: 生成测试报告
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.1
      if: always()
      with:
        reports: '**/TestResults/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura;Badges'
        
    - name: 上传测试结果
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/TestResults/*.trx
          coveragereport
        retention-days: 30
        
    - name: 发布覆盖率摘要
      uses: 5monkeys/cobertura-action@master
      if: always()
      with:
        path: '**/TestResults/coverage.cobertura.xml'
        minimum_coverage: 75
        show_line: true
        show_branch: true
        show_class_names: true
        only_changed_files: false 