<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>0786ec8e-8f03-4817-b1bc-2cd629e39b93</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ApiServices\CodeSpirit.ApprovalApi\CodeSpirit.ApprovalApi.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.ExamApi\CodeSpirit.ExamApi.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.FileStorageApi\CodeSpirit.FileStorageApi.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.ConfigCenter\CodeSpirit.ConfigCenter.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.IdentityApi\CodeSpirit.IdentityApi.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.MessagingApi\CodeSpirit.MessagingApi.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.PathfinderApi\CodeSpirit.PathfinderApi.csproj" />
		<ProjectReference Include="..\ApiServices\CodeSpirit.SurveyApi\CodeSpirit.SurveyApi.csproj" />
		<ProjectReference Include="..\CodeSpirit.Web\CodeSpirit.Web.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Elasticsearch" Version="13.0.0" />
		<PackageReference Include="Aspire.Hosting.Redis" Version="13.0.2" />
		<PackageReference Include="Aspire.Hosting.Seq" Version="13.0.2" />
		<PackageReference Include="Aspire.Hosting.SqlServer" Version="13.0.2" />
		<PackageReference Include="Aspire.Hosting.MySql" Version="13.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
		<PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.0.2" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Abstractions" Version="10.0.0" />
	</ItemGroup>

</Project>
